"use client";

import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

type Tournament={id:string;name:string;date:string|null;city:string|null;venue:string|null;sport:string|null;description:string|null;entry_fee:number;registration_deadline:string|null;status:string;is_public:boolean;poster_url:string|null;regulations_text:string|null};
type Poster={id:string;public_url:string;sort_order:number};
type Doc={id:string;name:string;storage_path:string;mime_type:string|null};

export default function TournamentSettingsPage(){
 const{id}=useParams<{id:string}>();const router=useRouter();
 const[t,setT]=useState<Tournament|null>(null);const[posters,setPosters]=useState<Poster[]>([]);const[doc,setDoc]=useState<Doc|null>(null);const[organizerId,setOrganizerId]=useState<string|null>(null);const[locale,setLocale]=useState<"ru"|"kk">("ru");
 const[form,setForm]=useState({name:"",date:"",city:"",venue:"",sport:"",description:"",entryFee:"0",registrationDeadline:"",status:"draft",isPublic:false,regulationsText:""});
 const[posterFiles,setPosterFiles]=useState<File[]>([]);const[regulations,setRegulations]=useState<File|null>(null);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[ok,setOk]=useState("");const ru=locale==="ru";
 useEffect(()=>{if(localStorage.getItem("tp-lang")==="kk")setLocale("kk")},[]);
 useEffect(()=>{(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){router.replace("/login");return}const{data:org}=await s.from("organizers").select("id").eq("user_id",user.id).maybeSingle();if(!org){router.replace("/organizer");return}setOrganizerId(org.id);
   const{data:tournament}=await s.from("tournaments").select("id,name,date,city,venue,sport,description,entry_fee,registration_deadline,status,is_public,poster_url,regulations_text").eq("id",id).maybeSingle();if(!tournament){router.replace("/organizer");return}setT(tournament);setForm({name:tournament.name,date:tournament.date||"",city:tournament.city||"",venue:tournament.venue||"",sport:tournament.sport||"",description:tournament.description||"",entryFee:String(tournament.entry_fee??0),registrationDeadline:tournament.registration_deadline?new Date(tournament.registration_deadline).toISOString().slice(0,16):"",status:tournament.status,isPublic:tournament.is_public,regulationsText:tournament.regulations_text||""});
   const{data:posterRows}=await s.from("tournament_posters").select("id,public_url,sort_order").eq("tournament_id",id).order("sort_order",{ascending:true});setPosters(posterRows||[]);
   const{data:docs}=await s.from("documents").select("id,name,storage_path,mime_type").eq("tournament_id",id).eq("is_public",true).order("created_at",{ascending:false}).limit(1);setDoc(docs?.[0]||null);
 })()},[id,router]);
 function update(k:keyof typeof form,v:string|boolean){setForm(x=>({...x,[k]:v}))}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");setOk("");const s=createClient();
   if(!form.name.trim()){setError(ru?"Введите название турнира.":"Турнир атауын енгізіңіз.");setSaving(false);return}
   if(posterFiles.length>5){setError(ru?"Можно загрузить максимум 5 афиш.":"Ең көбі 5 афиша жүктеуге болады.");setSaving(false);return}
   const{error:saveError}=await s.from("tournaments").update({name:form.name.trim(),date:form.date||null,city:form.city.trim()||null,venue:form.venue.trim()||null,sport:form.sport.trim()||null,description:form.description.trim()||null,entry_fee:Number(form.entryFee)||0,registration_deadline:form.registrationDeadline?new Date(form.registrationDeadline).toISOString():null,status:form.status,is_public:form.isPublic,regulations_text:form.regulationsText.trim()||null,updated_at:new Date().toISOString()}).eq("id",id);
   if(saveError){setError(saveError.message);setSaving(false);return}
   if(posterFiles.length){if(!organizerId){setError("Organizer profile not found");setSaving(false);return}const newRows:Poster[]=[];for(let i=0;i<posterFiles.length;i++){const poster=posterFiles[i];const path=`${organizerId}/${id}/${Date.now()}-${i}-${poster.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const{error:u}=await s.storage.from("posters").upload(path,poster,{upsert:false,contentType:poster.type||undefined});if(u){setError(`Афиша: ${u.message}`);setSaving(false);return}const{data:url}=s.storage.from("posters").getPublicUrl(path);const{data:row,error:e2}=await s.from("tournament_posters").insert({tournament_id:id,storage_path:path,public_url:url.publicUrl,sort_order:posters.length+i}).select("id,public_url,sort_order").single();if(e2||!row){setError(`Афиша: ${e2?.message||"не удалось сохранить"}`);setSaving(false);return}newRows.push(row)}if(posters.length===0){await s.from("tournaments").update({poster_url:newRows[0].public_url}).eq("id",id)}setPosters(x=>[...x,...newRows])}
   if(regulations){if(!organizerId){setError("Organizer profile not found");setSaving(false);return}const path=`${organizerId}/${id}/${Date.now()}-${regulations.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const{error:u}=await s.storage.from("regulations").upload(path,regulations,{upsert:false,contentType:regulations.type||undefined});if(u){setError(`Положение: ${u.message}`);setSaving(false);return}const{data:url}=s.storage.from("regulations").getPublicUrl(path);await s.from("documents").delete().eq("tournament_id",id);const{error:e2}=await s.from("documents").insert({tournament_id:id,name:regulations.name,storage_path:url.publicUrl,mime_type:regulations.type||null,is_public:true});if(e2){setError(`Положение: ${e2.message}`);setSaving(false);return}setDoc({id:"new",name:regulations.name,storage_path:url.publicUrl,mime_type:regulations.type||null})}
   setT(x=>x?{...x,...form,date:form.date||null,city:form.city||null,sport:form.sport||null,venue:form.venue||null,description:form.description||null,entry_fee:Number(form.entryFee)||0,registration_deadline:form.registrationDeadline||null,regulations_text:form.regulationsText||null}:x);setPosterFiles([]);setOk(ru?"Изменения сохранены.":"Өзгерістер сақталды.");setSaving(false);router.refresh()}
 if(!t)return <main className="container dashboard-page"><p className="muted">{ru?"Загрузка…":"Жүктелуде…"}</p></main>;
 return <main className="container dashboard-page"><div className="page-topline"><Link className="back-link" href={`/organizer/tournaments/${id}`}>← {ru?"Турнир":"Жарыс"}</Link></div><section className="form-card"><div className="eyebrow">{ru?"НАСТРОЙКИ":"БАПТАУЛАР"}</div><h1>{ru?"Управление турниром":"Жарысты басқару"}</h1><p className="muted">{ru?"После создания здесь заполняются все основные данные турнира.":"Жарыс жасалғаннан кейін барлық негізгі деректер осы жерде толтырылады."}</p>
 <form className="tournament-form" onSubmit={save}>
  <label>{ru?"Название":"Атауы"}<input className="field" value={form.name} onChange={e=>update("name",e.target.value)} required/></label>
  <div className="form-grid"><label>{ru?"Дата":"Күні"}<input className="field" type="date" value={form.date} onChange={e=>update("date",e.target.value)}/></label><label>{ru?"Город":"Қала"}<input className="field" value={form.city} onChange={e=>update("city",e.target.value)}/></label></div>
  <div className="form-grid"><label>{ru?"Вид спорта":"Спорт түрі"}<input className="field" value={form.sport} onChange={e=>update("sport",e.target.value)}/></label><label>{ru?"Место проведения":"Өтетін орын"}<input className="field" value={form.venue} onChange={e=>update("venue",e.target.value)}/></label></div>
  <div className="form-grid"><label>{ru?"Взнос":"Жарна"}<input className="field" type="number" min="0" value={form.entryFee} onChange={e=>update("entryFee",e.target.value)}/></label><label>{ru?"Дедлайн регистрации":"Тіркелу мерзімі"}<input className="field" type="datetime-local" value={form.registrationDeadline} onChange={e=>update("registrationDeadline",e.target.value)}/></label></div>
  <label>{ru?"Описание":"Сипаттама"}<textarea className="field textarea" rows={5} value={form.description} onChange={e=>update("description",e.target.value)}/></label>
  <div className="panel"><h2>{ru?"Афиши":"Афишалар"}</h2><p className="muted">{ru?`${posters.length}/5 загружено. Можно добавить ещё.`:`${posters.length}/5 жүктелді. Қосуға болады.`}</p>{posters.length>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(130px,1fr))",gap:10,marginBottom:14}}>{posters.map((p,i)=><div key={p.id}><img src={p.public_url} alt="" style={{width:"100%",aspectRatio:"3/4",objectFit:"contain",background:"#090a0c",borderRadius:10}}/><span className="muted">{i+1}</span></div>)}</div>}<label>{ru?"Добавить афиши":"Афиша қосу"}<input className="field" type="file" accept="image/*" multiple onChange={e=>setPosterFiles(Array.from(e.target.files||[]).slice(0,5-posters.length))}/></label></div>
  <div className="panel"><h2>{ru?"Положение":"Ереже"}</h2><label>{ru?"Текст положения":"Ереже мәтіні"}<textarea className="field textarea" rows={10} value={form.regulationsText} onChange={e=>update("regulationsText",e.target.value)} placeholder={ru?"Можно вставить положение текстом…":"Ережені мәтін түрінде енгізуге болады…"}/></label>{doc?<p><a href={doc.storage_path} target="_blank" rel="noreferrer">{ru?"Текущий файл":"Қазіргі файл"}: {doc.name}</a></p>:<p className="muted">{ru?"Файл положения не загружен.":"Ереже файлы жүктелмеген."}</p>}<label>{ru?"Загрузить файл положения":"Ереже файлын жүктеу"}<input className="field" type="file" accept=".pdf,.doc,.docx" onChange={e=>setRegulations(e.target.files?.[0]||null)}/></label></div>
  <label>{ru?"Этап турнира":"Жарыс кезеңі"}<select className="field" value={form.status} onChange={e=>update("status",e.target.value)}><option value="draft">{ru?"Черновик":"Жоба"}</option><option value="registration_open">{ru?"Регистрация открыта":"Тіркелу ашық"}</option><option value="registration_closed">{ru?"Регистрация закрыта":"Тіркелу жабық"}</option><option value="preparation">{ru?"Подготовка":"Дайындық"}</option><option value="running">{ru?"Идёт соревнование":"Жарыс өтіп жатыр"}</option><option value="completed">{ru?"Завершено":"Аяқталды"}</option></select></label>
  <label className="checkbox-row"><input type="checkbox" checked={form.isPublic} onChange={e=>update("isPublic",e.target.checked)}/>{ru?"Показывать турнир публично":"Жарысты көпшілікке көрсету"}</label>
  {error&&<p className="error" role="alert">{error}</p>}{ok&&<p className="success" role="status">{ok}</p>}<button className="primary" disabled={saving}>{saving?(ru?"Сохраняем…":"Сақталуда…"):(ru?"Сохранить изменения":"Өзгерістерді сақтау")}</button>
 </form></section></main>;
}
