"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Match={id:string;match_number:number;status:string;participant_a_id:string|null;participant_b_id:string|null;participantA:any;participantB:any};
type Schedule={match_id:string;scheduled_order:number|null;approximate_time:string|null;mat:any};
const person=(p:any)=>p?`${p.first_name} ${p.last_name}`.trim():"Ожидается участник";
const statusLabel=(s:string)=>({scheduled:"Запланирован",ready:"Готов",running:"Идёт сейчас",completed:"Завершён",cancelled:"Отменён"}[s]??s);
export default function LiveTournament({tournamentId,initialMatches,initialResults,initialSchedule}:{tournamentId:string;initialMatches:Match[];initialResults:any[];initialSchedule:Schedule[]}){const[matches,setMatches]=useState(initialMatches);const[results,setResults]=useState(initialResults);const[schedule,setSchedule]=useState(initialSchedule);useEffect(()=>{const s=createClient();const refreshSchedule=async()=>{const ids=matches.map(m=>m.id);if(!ids.length){setSchedule([]);return}const{data}=await s.from("match_schedule").select("match_id,scheduled_order,approximate_time,mats(name)").in("match_id",ids).order("scheduled_order");setSchedule((data??[]).map((x:any)=>({match_id:x.match_id,scheduled_order:x.scheduled_order,approximate_time:x.approximate_time,mat:Array.isArray(x.mats)?x.mats[0]??null:x.mats??null})))};const ch=s.channel(`public-tournament-${tournamentId}`).on("postgres_changes",{event:"*",schema:"public",table:"matches",filter:`tournament_id=eq.${tournamentId}`},async p=>{if(p.eventType==="DELETE"){setMatches(x=>x.filter(m=>m.id!==p.old.id));return}const m=p.new as any;const{data:a}=m.participant_a_id?await s.from("participants").select("first_name,last_name").eq("id",m.participant_a_id).maybeSingle():{data:null};const{data:b}=m.participant_b_id?await s.from("participants").select("first_name,last_name").eq("id",m.participant_b_id).maybeSingle():{data:null};const next={...m,participantA:a,participantB:b};setMatches(x=>x.some(v=>v.id===m.id)?x.map(v=>v.id===m.id?next:v):[...x,next].sort((a,b)=>a.match_number-b.match_number));}).on("postgres_changes",{event:"*",schema:"public",table:"match_schedule"},async()=>{await refreshSchedule()}).on("postgres_changes",{event:"*",schema:"public",table:"results",filter:`tournament_id=eq.${tournamentId}`},async()=>{const{data}=await s.from("results").select("place,category_id,participants(first_name,last_name)").eq("tournament_id",tournamentId).order("place");setResults(data??[])}).subscribe();return()=>{void s.removeChannel(ch)}},[tournamentId,matches.length]);
 return <>
  <section className="public-section"><h2>Расписание</h2><div className="category-list">{schedule.map((x,i)=>{const m=matches.find(v=>v.id===x.match_id);if(!m)return null;const mat=x.mat;return <article className="participant-card" key={x.match_id}><div className="participant-main"><strong>#{x.scheduled_order??i+1} · Бой #{m.match_number}</strong><span>{person(m.participantA)} — {person(m.participantB)}</span></div><span className="status-pill">{mat?.name??"Ковёр не назначен"}{x.approximate_time?` · ${new Date(x.approximate_time).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}`:""}</span></article>})}</div>{schedule.length===0&&<div className="empty-state">Расписание пока не опубликовано.</div>}</section>
  <section className="public-section"><h2>Сетка и бои</h2><div className="category-list">{matches.map(m=><article className="participant-card" key={m.id}><div className="participant-main"><strong>Бой #{m.match_number}</strong><span>{person(m.participantA)} — {person(m.participantB)}</span></div><span className="status-pill">{statusLabel(m.status)}</span></article>)}</div>{matches.length===0&&<div className="empty-state">Бои пока не сформированы.</div>}</section>
  <section className="public-section"><h2>Результаты</h2><div className="cards-grid">{results.map((r:any,i:number)=><article className="info-card" key={`${r.category_id}-${r.place}-${i}`}><div className="eyebrow">{r.place} МЕСТО</div><strong>{person(Array.isArray(r.participants)?r.participants[0]:r.participants)}</strong></article>)}</div>{results.length===0&&<div className="empty-state">Результатов пока нет.</div>}</section>
 </>;
}
