"use client";

import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { translations, type Locale } from "@/lib/i18n";

type Row = { id:string; participant_id:string; application_number:string|null; status:string; payment_status:string; first_name:string; last_name:string; age:number; weight:number; experience:string|null; phone:string|null; club:string|null; coach:string|null };

export default function ParticipantsClient({ tournamentId, initialRows }: { tournamentId:string; initialRows:Row[] }) {
  const [locale] = useState<Locale>(() => typeof window !== "undefined" && localStorage.getItem("tp-lang") === "kk" ? "kk" : "ru");
  const t = translations[locale];
  const [rows,setRows]=useState(initialRows); const [query,setQuery]=useState(""); const [statusFilter,setStatusFilter]=useState("all"); const [busy,setBusy]=useState<string|null>(null); const supabase=createClient();
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase(); return rows.filter(r=>{const text=[r.first_name,r.last_name,r.club,r.coach,r.application_number,r.phone].filter(Boolean).join(" ").toLowerCase(); return (!q||text.includes(q))&&(statusFilter==="all"||r.status===statusFilter);});},[rows,query,statusFilter]);
  async function updateRegistration(id:string,patch:{status?:string;payment_status?:string}){setBusy(id);const {data,error}=await supabase.from("registrations").update(patch).eq("id",id).eq("tournament_id",tournamentId).select("id,status,payment_status").single();if(!error&&data)setRows(c=>c.map(r=>r.id===id?{...r,...data}:r));if(error)window.alert(error.message);setBusy(null);}
  async function removeRegistration(id:string){if(!window.confirm(t.deleteApplication))return;setBusy(id);const {error}=await supabase.from("registrations").delete().eq("id",id).eq("tournament_id",tournamentId);if(!error)setRows(c=>c.filter(r=>r.id!==id));if(error)window.alert(error.message);setBusy(null);}
  const paidStatus = (r:Row) => r.payment_status === "paid";
  const confirmedStatus = (r:Row) => r.status === "confirmed";
  return <div className="participants-workspace"><div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.participantSearch}/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">{t.allStatuses}</option>{Object.entries(t.participantStatuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><div className="participants-list">{filtered.length===0?<div className="empty-state">{t.noApplications}</div>:filtered.map(r=><article className="participant-card" key={r.id}><div className="participant-main"><div><strong>{r.last_name} {r.first_name}</strong><span className="muted">#{r.application_number??"—"} · {r.age} {t.years} · {r.weight} кг</span></div><span className="status">{t.participantStatuses[r.status as keyof typeof t.participantStatuses]??r.status}</span></div><div className="participant-meta"><span>{r.club||t.clubNotSet}</span><span>{r.coach?`${t.coach}: ${r.coach}`:t.coachNotSet}</span><span>{r.experience||t.experienceNotSet}</span><span>{r.phone||t.phoneNotSet}</span><span>{t.payment}: {paidStatus(r)?t.paid:t.unpaid}</span></div><div className="participant-actions"><button disabled={busy===r.id} onClick={()=>updateRegistration(r.id,{payment_status:paidStatus(r)?"unpaid":"paid",status:paidStatus(r)?(confirmedStatus(r)?"payment_confirmed":"pending_confirmation"):"payment_confirmed"})}>{paidStatus(r)?t.cancelPayment:t.confirmPayment}</button><button disabled={busy===r.id||!paidStatus(r)} onClick={()=>updateRegistration(r.id,{status:confirmedStatus(r)?"payment_confirmed":"confirmed"})}>{confirmedStatus(r)?t.removeConfirmation:t.confirmApplication}</button><button className="danger-button" disabled={busy===r.id} onClick={()=>removeRegistration(r.id)}>{t.delete}</button></div></article>)}</div></div>;
}
