"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";

type Cat={id:string;name:string};
type Person={id:string;first_name:string;last_name:string;age:number;weight:number|null;actual_weight:number|null};
type Match={id:string;match_number:number;round_number:number;status:string;participant_a_id:string|null;participant_b_id:string|null;winner_id:string|null;next_match_id:string|null;category_id:string};
type Schedule={match_id:string;scheduled_order:number;approximate_time:string|null;mat:{name:string}|null};
type Config={zoneCount:number;startTime:string};
type ReadyCat=Cat&{count:number};
const personName=(p?:Person)=>p?`${p.first_name} ${p.last_name}`.trim():"Ожидается участник";
export default function BracketsClient({categories,initialConfig}:{categories:Cat[];initialConfig:Config}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[matches,setMatches]=useState<Match[]>([]),[people,setPeople]=useState<Record<string,Person>>({}),[schedule,setSchedule]=useState<Schedule[]>([]),[selected,setSelected]=useState("all"),[readyCats,setReadyCats]=useState<ReadyCat[]>([]);
 const [zoneCountInput,setZoneCountInput]=useState(String(initialConfig.zoneCount||1)),[startTime,setStartTime]=useState(initialConfig.startTime||"10:00"),[configured,setConfigured]=useState(Boolean(initialConfig.startTime));
 const s=createClient(); const tournamentId=typeof window!=="undefined"?(window.location.pathname.match(/tournaments\/([^/]+)/)||[])[1]:"";
 const kk=typeof window!=="undefined"&&localStorage.getItem("tp-lang")==="kk";
 const L=kk?{title:"Жекпе-жек торы және кесте",schedule:"Турнир кестесі",zones:"Жекпе-жек аймақтары",start:"Басталу уақыты",save:"Сақтау",saved:"Сақталды.",form:"Торларды қалыптастыру",forming:"Қалыптастырылуда…",ready:"Қалыптастыруға дайын санаттар",noneReady:"Әзірге қалыптастыруға дайын санаттар жоқ.",all:"Барлық санаттар",cat:"Санат",winner:"Жеңіс",approx:"Спортшы карточкасындағы уақыт шамамен көрсетілген және жарыстың өту барысына қарай жаңартылады.",up:"Жоғары",down:"Төмен",empty:"Жекпе-жектер әлі қалыптастырылған жоқ.",completed:"Аяқталды",running:"Өтіп жатыр",scheduled:"Жоспарда",cancelled:"Болдырылмады",invalidZones:"Аймақтар санын 1-ден 26-ға дейін енгізіңіз",zoneWord:"Аймақ",participant:"қатысушы"}:{title:"Сетка и расписание",schedule:"Расписание турнира",zones:"Зоны поединков",start:"Начало соревнований",save:"Сохранить",saved:"Настройки сохранены.",form:"Сформировать сетки",forming:"Формируем…",ready:"Готовые к формированию категории",noneReady:"Пока нет категорий, готовых к формированию сетки.",all:"Все существующие сетки",cat:"Категория",winner:"Победа",approx:"Время на карточке спортсмена указано приблизительно и обновляется по ходу соревнований.",up:"Выше",down:"Ниже",empty:"Бои ещё не сформированы.",completed:"Завершён",running:"Идёт",scheduled:"Запланирован",cancelled:"Отменён",invalidZones:"Введите количество зон от 1 до 26",zoneWord:"Зона",participant:"участника"};
 const zoneCount=Number(zoneCountInput),catMap=useMemo(()=>Object.fromEntries(categories.map(c=>[c.id,c.name])),[categories]);
 const formedCategoryIds=useMemo(()=>new Set(matches.map(m=>m.category_id)),[matches]);
 const formedCategories=useMemo(()=>categories.filter(c=>formedCategoryIds.has(c.id)),[categories,formedCategoryIds]);
 const orderedMatches=useMemo(()=>{const ids=new Set(schedule.map(x=>x.match_id));const a=schedule.map(x=>matches.find(m=>m.id===x.match_id)).filter(Boolean) as Match[];const b=matches.filter(m=>!ids.has(m.id)).sort((x,y)=>x.round_number-y.round_number||x.match_number-y.match_number);return [...a,...b]},[schedule,matches]);
 const positionMap=useMemo(()=>Object.fromEntries(orderedMatches.map((m,i)=>[m.id,i])),[orderedMatches]);
 async function load(){
  const {data:m,error}=await s.from("matches").select("id,match_number,round_number,status,participant_a_id,participant_b_id,winner_id,next_match_id,category_id").eq("tournament_id",tournamentId).order("match_number");
  if(error){setMessage(error.message);return}
  const ids=[...new Set((m??[]).flatMap(x=>[x.participant_a_id,x.participant_b_id,x.winner_id]).filter(Boolean) as string[])];const map:Record<string,Person>={};
  if(ids.length){const{data:p}=await s.from("participants").select("id,first_name,last_name,age,weight,actual_weight").in("id",ids);for(const x of p??[])map[x.id]=x}
  const{data:sch}=await s.from("match_schedule").select("match_id,scheduled_order,approximate_time,mats(name)").order("scheduled_order");
  setMatches(m??[]);setPeople(map);setSchedule((sch??[]).map((x:any)=>({match_id:x.match_id,scheduled_order:x.scheduled_order,approximate_time:x.approximate_time,mat:Array.isArray(x.mats)?x.mats[0]??null:x.mats??null})));
  const cids=categories.map(c=>c.id);if(cids.length){const{data:cp}=await s.from("category_participants").select("category_id,participant_id,is_active,weigh_in_status").in("category_id",cids);const pids=[...new Set((cp??[]).filter(x=>x.is_active&&x.weigh_in_status==="in_weight").map(x=>x.participant_id))];const{data:rg}=pids.length?await s.from("registrations").select("participant_id,status,payment_status").eq("tournament_id",tournamentId).in("participant_id",pids):{data:[] as any[]};const paid=new Set((rg??[]).filter(x=>x.status==="confirmed"&&x.payment_status==="paid").map(x=>x.participant_id));const counts=new Map<string,number>();for(const x of cp??[])if(x.is_active&&x.weigh_in_status==="in_weight"&&paid.has(x.participant_id))counts.set(x.category_id,(counts.get(x.category_id)||0)+1);const existingBrackets=new Set((m??[]).map(x=>x.category_id));setReadyCats(categories.map(c=>({...c,count:counts.get(c.id)||0})).filter(c=>c.count>=2&&!existingBrackets.has(c.id)));}
 }
 useEffect(()=>{void load()},[]);
 async function saveSchedule(){const parsed=Number(zoneCountInput);if(!Number.isInteger(parsed)||parsed<1||parsed>26){setMessage(L.invalidZones);return}setBusy(true);setMessage("");const{error}=await s.rpc("configure_tournament_schedule",{p_tournament_id:tournamentId,p_zone_count:parsed,p_start_time:startTime});if(error){setMessage(error.message);setBusy(false);return}setZoneCountInput(String(parsed));setConfigured(true);if(matches.length){const{error:scheduleError}=await s.rpc("generate_tournament_schedule",{p_tournament_id:tournamentId});if(scheduleError){setMessage(scheduleError.message);setBusy(false);return}}setMessage(L.saved);await load();setBusy(false)}
 async function formBrackets(){setBusy(true);setMessage("");for(const c of readyCats){const{error}=await s.rpc("generate_single_elimination_bracket",{p_category_id:c.id});if(error){setMessage(error.message);setBusy(false);return}}if(configured){const{error}=await s.rpc("generate_tournament_schedule",{p_tournament_id:tournamentId});if(error){setMessage(error.message);setBusy(false);return}}setMessage(kk?"Торлар қалыптастырылды.":"Сетки сформированы.");await load();setBusy(false)}
 async function reorder(matchId:string,dir:-1|1){const ids=orderedMatches.map(m=>m.id);const i=ids.indexOf(matchId),j=i+dir;if(i<0||j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];setBusy(true);const{error}=await s.rpc("reorder_tournament_schedule",{p_tournament_id:tournamentId,p_match_ids:ids.filter(id=>schedule.some(x=>x.match_id===id))});if(error)setMessage(error.message);else await load();setBusy(false)}
 async function winner(m:Match,id:string){if(m.status==="completed"||!id)return;setBusy(true);setMessage("");const{error}=await s.rpc("record_match_winner",{p_match_id:m.id,p_winner_id:id});if(error)setMessage(error.message);else await load();setBusy(false)}
 const scheduleByMatch=Object.fromEntries(schedule.map(x=>[x.match_id,x]));\n const waitingFor=(m:Match,side:"a"|"b")=>{if((side==="a"?m.participant_a_id:m.participant_b_id))return null;const prev=matches.find(x=>x.next_match_id===m.id);return prev?`Ожидается победитель боя #${prev.match_number}`:"Ожидается участник"};
 useEffect(()=>{if(selected!=="all"&&!formedCategoryIds.has(selected))setSelected("all")},[selected,formedCategoryIds]);
 return <section className="brackets-workspace">
  <div className="form-card"><div className="eyebrow">{L.schedule}</div><h2>{L.schedule}</h2><div className="bracket-editor-grid"><label>{L.zones}<input className="field" type="number" min={1} max={26} value={zoneCountInput} onChange={e=>setZoneCountInput(e.target.value.replace(/[^0-9]/g,""))}/></label><label>{L.start}<input className="field" type="time" value={startTime} onChange={e=>setStartTime(e.target.value)}/></label></div><button type="button" className="primary" disabled={busy} onClick={()=>void saveSchedule()} style={{marginTop:12}}>{L.save}</button><p className="muted" style={{marginTop:10}}>{Number.isInteger(zoneCount)&&zoneCount>=1&&zoneCount<=26?Array.from({length:zoneCount},(_,i)=>`${L.zoneWord} ${String.fromCharCode(65+i)}`).join(" · "):""}</p></div>
  <div className="form-card"><div className="eyebrow">{L.title}</div><h2>{L.form}</h2><p className="muted">{L.ready}</p>{readyCats.length?<div style={{display:"grid",gap:8,marginBottom:12}}>{readyCats.map(c=><div key={c.id} style={{display:"flex",justifyContent:"space-between",gap:12}}><strong>{c.name}</strong><span className="muted">{c.count} {L.participant}</span></div>)}</div>:<p className="muted">{L.noneReady}</p>}<button type="button" className="primary" disabled={busy||!readyCats.length} onClick={()=>void formBrackets()}>{busy?L.forming:L.form}</button></div>
  {formedCategories.length>0&&<div className="form-card"><label>{L.cat}<select className="field" value={selected} onChange={e=>setSelected(e.target.value)}><option value="all">{L.all}</option>{formedCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>}
  <div className="category-list">{orderedMatches.filter(m=>selected==="all"||m.category_id===selected).map(m=>{const sc=scheduleByMatch[m.id];const pos=positionMap[m.id];const fightNo=sc?.scheduled_order??m.match_number;return <article key={m.id} className="participant-card" style={{display:"grid",gridTemplateColumns:"minmax(0,1fr)",width:"100%",minWidth:0,overflow:"hidden",gap:10}}><div style={{display:"grid",gridTemplateColumns:"auto minmax(0,1fr)",gap:12,alignItems:"center",minWidth:0}}><strong style={{fontSize:18,whiteSpace:"nowrap"}}>#{fightNo}</strong><span style={{fontWeight:800,minWidth:0,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{catMap[m.category_id]||""}</span></div><div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:10,alignItems:"center",minWidth:0}}><strong style={{minWidth:0,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{m.participant_a_id?personName(people[m.participant_a_id]):waitingFor(m,"a")}</strong><button type="button" className="primary" style={{whiteSpace:"nowrap"}} disabled={busy||m.status==="completed"||!m.participant_a_id} onClick={()=>m.participant_a_id&&void winner(m,m.participant_a_id)}>{L.winner}</button></div><div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:10,alignItems:"center",minWidth:0}}><strong style={{minWidth:0,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{m.participant_b_id?personName(people[m.participant_b_id]):waitingFor(m,"b")}</strong><button type="button" className="primary" style={{whiteSpace:"nowrap"}} disabled={busy||m.status==="completed"||!m.participant_b_id} onClick={()=>m.participant_b_id&&void winner(m,m.participant_b_id)}>{L.winner}</button></div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><button type="button" className="secondary" disabled={busy||pos===0} onClick={()=>void reorder(m.id,-1)}>{L.up}</button><button type="button" className="secondary" disabled={busy||pos===orderedMatches.length-1} onClick={()=>void reorder(m.id,1)}>{L.down}</button><span className="status-pill" style={{marginTop:0}}>{m.status==="completed"?L.completed:m.status==="in_progress"?L.running:m.status==="cancelled"?L.cancelled:L.scheduled}</span></div></article>})}</div>{orderedMatches.length===0&&<div className="empty-state">{L.empty}</div>}{schedule.length>0&&<p className="muted">{L.approx}</p>}
 </section>;
}
