"use client";

import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { translations, type Locale } from "@/lib/i18n";

type Person={id:string;first_name:string;last_name:string;age:number;weight:number;club:string|null;coach:string|null};
type Category={id:string;name:string;age_min:number|null;age_max:number|null;weight_limit:number|null;weight_allowance:number|null;sort_order:number;participantCount:number};

export default function CategoriesClient({tournamentId,initialCategories,participants,initialAssignments}:{tournamentId:string;initialCategories:Category[];participants:Person[];initialAssignments:Record<string,string>}){
 const [locale]=useState<Locale>(()=>typeof window!=="undefined"&&localStorage.getItem("tp-lang")==="kk"?"kk":"ru"); const t=translations[locale];
 const labels=locale==="kk"?{allowance:"Рұқсат",preview:"Санат атауы",previewEmpty:"Жас пен салмақты енгізіңіз",details:"Санат қатысушылары",info:"Санатқа бекітілген қатысушылар тізімі.",declared:"Мәлімделген салмақ",kg:"кг",open:"Ашу",close:"Жабу"}:{allowance:"Допуск по весу",preview:"Название категории",previewEmpty:"Укажите возраст и вес",details:"Участники категории",info:"Список участников, закреплённых за этой категорией.",declared:"Заявленный вес",kg:"кг",open:"Открыть",close:"Закрыть"};
 const [categories,setCategories]=useState(initialCategories);const [selectedCategory,setSelectedCategory]=useState("");const [assigned,setAssigned]=useState(initialAssignments);const [form,setForm]=useState({ageMin:"",ageMax:"",weight:"",allowance:""});const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState("");const supabase=createClient();
 const generatedName=useMemo(()=>{const age=form.ageMin&&form.ageMax?`${form.ageMin}–${form.ageMax} ${locale==="kk"?"жас":"лет"}`:"";const weight=form.weight?`${locale==="kk"?"дейін":"до"} ${form.weight} кг`:"";return [age,weight].filter(Boolean).join(" · ")},[form.ageMin,form.ageMax,form.weight,locale]);
 async function createCategory(e:React.FormEvent){e.preventDefault();setBusy("category");setError("");if(!form.ageMin||!form.ageMax||!form.weight){setError(labels.previewEmpty);setBusy(null);return}const {data,error}=await supabase.from("categories").insert({tournament_id:tournamentId,name:generatedName,age_min:Number(form.ageMin),age_max:Number(form.ageMax),weight_limit:Number(form.weight),weight_allowance:form.allowance?Number(form.allowance):0,sort_order:categories.length}).select("id,name,age_min,age_max,weight_limit,weight_allowance,sort_order").single();if(error||!data)setError(error?.message??t.errorGeneric);else{setCategories(c=>[...c,{...data,participantCount:0}]);setSelectedCategory(data.id);setForm({ageMin:"",ageMax:"",weight:"",allowance:""});}setBusy(null);}
 async function remove(id:string){if(!window.confirm(t.deleteCategory))return;setBusy(`delete:${id}`);const {error}=await supabase.from("categories").delete().eq("id",id).eq("tournament_id",tournamentId);if(!error){setCategories(c=>c.filter(x=>x.id!==id));if(selectedCategory===id)setSelectedCategory("");}else setError(error.message);setBusy(null);}
 async function assign(participantId:string,targetCategory:string){if(!targetCategory)return;setBusy(`assign:${participantId}`);setError("");const existing=assigned[participantId];if(existing===targetCategory){setBusy(null);return;}if(existing){const {error}=await supabase.from("category_participants").update({is_active:false}).eq("category_id",existing).eq("participant_id",participantId);if(error){setError(error.message);setBusy(null);return;}}const {data:existingRow}=await supabase.from("category_participants").select("category_id").eq("category_id",targetCategory).eq("participant_id",participantId).maybeSingle();let error;if(existingRow){({error}=await supabase.from("category_participants").update({is_active:true,weigh_in_status:"pending",weigh_in_weight:null}).eq("category_id",targetCategory).eq("participant_id",participantId));}else{({error}=await supabase.from("category_participants").insert({category_id:targetCategory,participant_id:participantId,is_active:true,weigh_in_status:"pending"}));}if(error){setError(error.message);setBusy(null);return;}setAssigned(x=>({...x,[participantId]:targetCategory}));setCategories(x=>x.map(c=>c.id===targetCategory?{...c,participantCount:c.participantCount+1}:existing===c.id?{...c,participantCount:Math.max(0,c.participantCount-1)}:c));setBusy(null);}
 async function unassign(participantId:string){const categoryId=assigned[participantId];if(!categoryId)return;setBusy(`unassign:${participantId}`);setError("");const {error}=await supabase.from("category_participants").update({is_active:false}).eq("category_id",categoryId).eq("participant_id",participantId);if(error){setError(error.message);setBusy(null);return;}setAssigned(x=>{const next={...x};delete next[participantId];return next});setCategories(x=>x.map(c=>c.id===categoryId?{...c,participantCount:Math.max(0,c.participantCount-1)}:c));setBusy(null);}
 const categoryParticipants=useMemo(()=>selectedCategory?participants.filter(p=>assigned[p.id]===selectedCategory):[],[participants,assigned,selectedCategory]);
 return <section className="categories-workspace"><form className="form-card compact-form" onSubmit={createCategory}><h2>{t.newCategory}</h2><div className="form-grid"><label>{t.ageFrom}<input className="field" type="number" min="0" required value={form.ageMin} onChange={e=>setForm({...form,ageMin:e.target.value})}/></label><label>{t.ageTo}<input className="field" type="number" min="0" required value={form.ageMax} onChange={e=>setForm({...form,ageMax:e.target.value})}/></label></div><div className="form-grid"><label>{t.weightLimit}<input className="field" type="number" min="0" step="0.1" required value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})}/></label><label>{labels.allowance}<input className="field" type="number" min="0" step="0.1" value={form.allowance} onChange={e=>setForm({...form,allowance:e.target.value})} placeholder="+1"/></label></div><div className="muted">{labels.preview}: <strong>{generatedName||labels.previewEmpty}</strong></div>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy!==null}>{busy==="category"?t.creating:t.createCategory}</button></form><div className="category-list">{categories.length===0?<div className="empty-state">{t.noCategories}</div>:categories.map(c=>{const open=selectedCategory===c.id;return <article className="participant-card" key={c.id}><div className="participant-main"><div><strong>{c.name}</strong><span className="muted">{c.age_min??"—"}–{c.age_max??"—"} {t.years} · {t.weightLimit.toLowerCase()} {c.weight_limit??"—"} кг · {labels.allowance.toLowerCase()} +{c.weight_allowance??0} кг · {c.participantCount} {t.participantsCount}</span></div><div className="participant-actions"><button type="button" className={open?"primary":"secondary"} disabled={busy!==null} onClick={()=>setSelectedCategory(open?"":c.id)}>{open?labels.close:labels.open}</button><button type="button" className="danger-button" disabled={busy!==null} onClick={()=>void remove(c.id)}>{t.delete}</button></div></div>{open&&<div className="form-card" style={{marginTop:16}}><h2>{labels.details}</h2><p className="muted">{labels.info}</p>{categoryParticipants.length===0?<div className="empty-state">{t.noFreeParticipants}</div>:<div className="participants-list">{categoryParticipants.map(p=><article className="participant-card" key={p.id}><div className="participant-main"><div><strong>{p.last_name} {p.first_name}</strong><span className="muted">{labels.declared}: {p.weight} {labels.kg} · {p.age} {t.years} · {p.club||t.clubNotSet}{p.coach?` · ${p.coach}`:""}</span></div><button type="button" className="danger-button" disabled={busy!==null} onClick={()=>void unassign(p.id)}>{t.remove}</button></div></article>)}</div>}</div>}</article>})}</div></section>;
}
