"use client";

import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { translations, type Locale } from "@/lib/i18n";

type Person={id:string;first_name:string;last_name:string;age:number;weight:number;club:string|null;coach:string|null};
type Category={id:string;name:string;age_min:number|null;age_max:number|null;weight_limit:number|null;weight_allowance:number|null;sort_order:number;participantCount:number};

export default function CategoriesClient({tournamentId,initialCategories,participants,initialAssignments}:{tournamentId:string;initialCategories:Category[];participants:Person[];initialAssignments:Record<string,string>}){
 const [locale]=useState<Locale>(()=>typeof window!=="undefined"&&localStorage.getItem("tp-lang")==="kk"?"kk":"ru"); const t=translations[locale];
 const labels=locale==="kk"?{allowance:"Рұқсат",preview:"Санат атауы",previewEmpty:"Жас пен салмақты енгізіңіз",notSet:"көрсетілмеген"}:{allowance:"Допуск по весу",preview:"Название категории",previewEmpty:"Укажите возраст и вес",notSet:"не указан"};
 const [categories,setCategories]=useState(initialCategories);const [selectedCategory,setSelectedCategory]=useState(initialCategories[0]?.id??"");const [assigned,setAssigned]=useState(initialAssignments);const [form,setForm]=useState({ageMin:"",ageMax:"",weight:"",allowance:""});const [busy,setBusy]=useState(false);const [error,setError]=useState("");const supabase=createClient();
 const generatedName=useMemo(()=>{const age=form.ageMin&&form.ageMax?`${form.ageMin}–${form.ageMax} ${locale==="kk"?"жас":"лет"}`:"";const weight=form.weight?`${locale==="kk"?"дейін":"до"} ${form.weight} кг`:"";return [age,weight].filter(Boolean).join(" · ")},[form.ageMin,form.ageMax,form.weight,locale]);
 async function createCategory(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");if(!form.ageMin||!form.ageMax||!form.weight){setError(labels.previewEmpty);setBusy(false);return}const {data,error}=await supabase.from("categories").insert({tournament_id:tournamentId,name:generatedName,age_min:Number(form.ageMin),age_max:Number(form.ageMax),weight_limit:Number(form.weight),weight_allowance:form.allowance?Number(form.allowance):0,sort_order:categories.length}).select("id,name,age_min,age_max,weight_limit,weight_allowance,sort_order").single();if(error||!data)setError(error?.message??t.errorGeneric);else{setCategories(c=>[...c,{...data,participantCount:0}]);setSelectedCategory(data.id);setForm({ageMin:"",ageMax:"",weight:"",allowance:""});}setBusy(false);}
 async function remove(id:string){if(!window.confirm(t.deleteCategory))return;const {error}=await supabase.from("categories").delete().eq("id",id).eq("tournament_id",tournamentId);if(!error){setCategories(c=>c.filter(x=>x.id!==id));if(selectedCategory===id)setSelectedCategory(categories.find(x=>x.id!==id)?.id??"");}else setError(error.message);}
 async function assign(participantId:string){if(!selectedCategory)return;setBusy(true);setError("");const existing=assigned[participantId];if(existing===selectedCategory){setBusy(false);return;}if(existing){const {error}=await supabase.from("category_participants").update({is_active:false}).eq("category_id",existing).eq("participant_id",participantId);if(error){setError(error.message);setBusy(false);return;}}const {data:existingRow}=await supabase.from("category_participants").select("category_id").eq("category_id",selectedCategory).eq("participant_id",participantId).maybeSingle();let error;if(existingRow){({error}=await supabase.from("category_participants").update({is_active:true}).eq("category_id",selectedCategory).eq("participant_id",participantId));}else{({error}=await supabase.from("category_participants").insert({category_id:selectedCategory,participant_id:participantId,is_active:true}));}if(error){setError(error.message);setBusy(false);return;}setAssigned(x=>({...x,[participantId]:selectedCategory}));setCategories(x=>x.map(c=>c.id===selectedCategory?{...c,participantCount:c.participantCount+1}:existing===c.id?{...c,participantCount:Math.max(0,c.participantCount-1)}:c));setBusy(false);}
 async function unassign(participantId:string){const categoryId=assigned[participantId];if(!categoryId)return;setBusy(true);setError("");const {error}=await supabase.from("category_participants").update({is_active:false}).eq("category_id",categoryId).eq("participant_id",participantId);if(error){setError(error.message);setBusy(false);return;}setAssigned(x=>{const next={...x};delete next[participantId];return next;});setCategories(x=>x.map(c=>c.id===categoryId?{...c,participantCount:Math.max(0,c.participantCount-1)}:c));setBusy(false);}
 const visibleParticipants=useMemo(()=>participants.filter(p=>!assigned[p.id]||assigned[p.id]===selectedCategory),[participants,assigned,selectedCategory]);const selected=categories.find(c=>c.id===selectedCategory);
 return <section className="categories-workspace"><form className="form-card compact-form" onSubmit={createCategory}><h2>{t.newCategory}</h2><div className="form-grid"><label>{t.ageFrom}<input className="field" type="number" min="0" required value={form.ageMin} onChange={e=>setForm({...form,ageMin:e.target.value})}/></label><label>{t.ageTo}<input className="field" type="number" min="0" required value={form.ageMax} onChange={e=>setForm({...form,ageMax:e.target.value})}/></label></div><div className="form-grid"><label>{t.weightLimit}<input className="field" type="number" min="0" step="0.1" required value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})}/></label><label>{labels.allowance}<input className="field" type="number" min="0" step="0.1" value={form.allowance} onChange={e=>setForm({...form,allowance:e.target.value})} placeholder="+1"/></label></div><div className="muted">{labels.preview}: <strong>{generatedName||labels.previewEmpty}</strong></div>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?t.creating:t.createCategory}</button></form><div className="category-list">{categories.length===0?<div className="empty-state">{t.noCategories}</div>:categories.map(c=><article className="participant-card" key={c.id}><div className="participant-main"><div><strong>{c.name}</strong><span className="muted">{c.age_min??"—"}–{c.age_max??"—"} {t.years} · {t.weightLimit.toLowerCase()} {c.weight_limit??"—"} кг · {labels.allowance.toLowerCase()} +{c.weight_allowance??0} кг · {c.participantCount} {t.participantsCount}</span></div><div className="participant-actions"><button className={selectedCategory===c.id?"primary":""} onClick={()=>setSelectedCategory(c.id)}>{t.openCategory}</button><button className="danger-button" onClick={()=>remove(c.id)}>{t.delete}</button></div></div></article>)}</div>{selected&&<div className="form-card"><h2>{t.categoryParticipants}: {selected.name}</h2><p className="muted">{t.addParticipantsHint}</p>{visibleParticipants.length===0?<div className="empty-state">{t.noFreeParticipants}</div>:<div className="participants-list">{visibleParticipants.map(p=>{const inCategory=assigned[p.id]===selectedCategory;return <article className="participant-card" key={p.id}><div className="participant-main"><div><strong>{p.last_name} {p.first_name}</strong><span className="muted">{p.age} {t.years} · {p.weight} кг · {p.club||t.clubNotSet}{p.coach?` · ${p.coach}`:""}</span></div><button disabled={busy} className={inCategory?"danger-button":"primary"} onClick={()=>inCategory?unassign(p.id):assign(p.id)}>{inCategory?t.remove:t.add}</button></div></article>})}</div>}{selected.participantCount<2&&<p className="muted">{t.fewParticipants}</p>}</div>}</section>;
}
