"use client";

import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { translations, type Locale } from "@/lib/i18n";

type Person={id:string;first_name:string;last_name:string;age:number;weight:number;club:string|null;coach:string|null};
type Category={id:string;name:string;age_min:number|null;age_max:number|null;weight_limit:number|null;weight_allowance:number|null;participantCount:number};
type WeighIn={categoryId:string;weight:number|null;status:"pending"|"in_weight"|"out_of_weight"};

export default function WeighInClient({initialCategories,participants,initialAssignments,initialWeighIns}:{tournamentId:string;initialCategories:Category[];participants:Person[];initialAssignments:Record<string,string>;initialWeighIns:Record<string,WeighIn>}){
 const [locale]=useState<Locale>(()=>typeof window!=="undefined"&&localStorage.getItem("tp-lang")==="kk"?"kk":"ru"); const t=translations[locale];
 const l=locale==="kk"?{declared:"Мәлімделген салмақ",actual:"Нақты салмақ",pending:"Өлшенбеген",inWeight:"Салмақта",outWeight:"Салмақта емес",confirmIn:"Салмақта",confirmOut:"Салмақта емес",move:"Басқа санатқа ауыстыру",remove:"Санаттан шығару",kg:"кг",empty:"Бұл санатта қатысушы жоқ",invalid:"Дұрыс салмақ енгізіңіз.",enterActual:"Алдымен нақты салмақты енгізіңіз."}:{declared:"Заявленный вес",actual:"Фактический вес",pending:"Не взвешен",inWeight:"В весе",outWeight:"Не в весе",confirmIn:"В весе",confirmOut:"Не в весе",move:"Перевести в категорию",remove:"Убрать из категории",kg:"кг",empty:"В этой категории нет участников",invalid:"Введите корректный вес.",enterActual:"Сначала введите фактический вес."};
 const [categories,setCategories]=useState(initialCategories);const [selected,setSelected]=useState(initialCategories[0]?.id??"");const [assigned,setAssigned]=useState(initialAssignments);const [weighIns,setWeighIns]=useState(initialWeighIns);const [moveTarget,setMoveTarget]=useState<Record<string,string>>({});const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState("");const supabase=createClient();
 const category=categories.find(c=>c.id===selected);const categoryParticipants=useMemo(()=>participants.filter(p=>assigned[p.id]===selected),[participants,assigned,selected]);
 function saveWeight(id:string,value:string){if(value.trim()===""){setError("");setWeighIns(x=>({...x,[id]:{categoryId:x[id]?.categoryId??assigned[id],weight:null,status:"pending"}}));return;}const n=Number(value);if(!Number.isFinite(n)||n<=0){setError(l.invalid);return;}setError("");setWeighIns(x=>({...x,[id]:{categoryId:x[id]?.categoryId??assigned[id],weight:n,status:"pending"}}));}
 async function setStatus(id:string,status:"in_weight"|"out_of_weight"){const wi=weighIns[id];const categoryId=wi?.categoryId??assigned[id];if(!categoryId){setError(l.invalid);return;}if(wi?.weight==null){setError(l.enterActual);return;}setBusy(`weigh:${id}`);setError("");const {data,error}=await supabase.rpc("set_category_weigh_in",{p_category_id:categoryId,p_participant_id:id,p_actual_weight:wi.weight,p_status:status});if(error)setError(error.message);else setWeighIns(x=>({...x,[id]:{categoryId,weight:wi.weight,status:data?.weigh_in_status??status}}));setBusy(null);}
 async function move(id:string){const target=moveTarget[id];const current=assigned[id];if(!target||!current)return;setBusy(`move:${id}`);setError("");const {data,error}=await supabase.rpc("transfer_category_participant",{p_from_category_id:current,p_to_category_id:target,p_participant_id:id});if(error){setError(error.message);setBusy(null);return;}const actual=Number(data?.actual_weight??weighIns[id]?.weight??0);setAssigned(x=>({...x,[id]:target}));setWeighIns(x=>({...x,[id]:{categoryId:target,weight:actual,status:"in_weight"}}));setCategories(x=>x.map(c=>c.id===current?{...c,participantCount:Math.max(0,c.participantCount-1)}:c.id===target?{...c,participantCount:c.participantCount+1}:c));setMoveTarget(x=>{const n={...x};delete n[id];return n});setBusy(null);}
 async function remove(id:string){const current=assigned[id];if(!current)return;setBusy(`remove:${id}`);setError("");const {error}=await supabase.from("category_participants").update({is_active:false}).eq("category_id",current).eq("participant_id",id);if(error){setError(error.message);setBusy(null);return;}setAssigned(x=>{const n={...x};delete n[id];return n});setCategories(x=>x.map(c=>c.id===current?{...c,participantCount:Math.max(0,c.participantCount-1)}:c));setBusy(null);}
 return <section className="categories-workspace"><div className="form-card"><label><strong>{locale==="kk"?"Салмақ санаты":"Весовая категория"}</strong><select className="field" value={selected} onChange={e=>setSelected(e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name} · {c.participantCount}</option>)}</select></label></div>{error&&<p className="error">{error}</p>}{category&&<div className="form-card"><h2>{category.name}</h2><p className="muted">{locale==="kk"?"Лимит":"Лимит"}: {category.weight_limit??"—"} {l.kg} · {locale==="kk"?"Рұқсат":"Допуск"}: +{category.weight_allowance??0} {l.kg}</p>{categoryParticipants.length===0?<div className="empty-state">{l.empty}</div>:<div className="participants-list">{categoryParticipants.map(p=>{const wi=weighIns[p.id];const rowBusy=busy===`weigh:${p.id}`||busy===`move:${p.id}`||busy===`remove:${p.id}`;return <article className="participant-card" key={p.id}><div className="participant-main"><div><strong>{p.last_name} {p.first_name}</strong><span className="muted">{l.declared}: {p.weight} {l.kg} · {p.age} {t.years} · {p.club||t.clubNotSet}{p.coach?` · ${p.coach}`:""}</span><div style={{display:"flex",gap:8,alignItems:"end",flexWrap:"wrap",marginTop:10}}><label><span className="muted">{l.actual}</span><input className="field" style={{width:130}} type="number" min="0" step="0.1" value={wi?.weight??""} placeholder={`${p.weight}`} onChange={e=>saveWeight(p.id,e.target.value)}/></label><button type="button" className={wi?.status==="in_weight"?"primary":"secondary"} disabled={rowBusy} onClick={()=>void setStatus(p.id,"in_weight")}>{l.confirmIn}</button><button type="button" className={wi?.status==="out_of_weight"?"danger-button":"secondary"} disabled={rowBusy} onClick={()=>void setStatus(p.id,"out_of_weight")}>{l.confirmOut}</button></div><span className="muted">{wi?.weight==null?l.enterActual:wi?.status==="pending"?l.pending:wi?.status==="in_weight"?l.inWeight:l.outWeight}</span>{wi?.status==="out_of_weight"&&<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:10}}><select className="field" value={moveTarget[p.id]??""} onChange={e=>setMoveTarget(x=>({...x,[p.id]:e.target.value}))}><option value="">{l.move}</option>{categories.filter(c=>c.id!==selected&&(c.age_min==null||p.age>=c.age_min)&&(c.age_max==null||p.age<=c.age_max)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button type="button" className="secondary" disabled={rowBusy||!moveTarget[p.id]} onClick={()=>void move(p.id)}>→</button></div>}</div><button type="button" className="danger-button" disabled={rowBusy} onClick={()=>void remove(p.id)}>{l.remove}</button></div></article>})}</div>}</div>}</section>;
}
