import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
const statusLabels: Record<string, string> = { draft: "Черновик", registration_open: "Регистрация открыта", registration_closed: "Регистрация закрыта", preparation: "Подготовка", running: "Идёт соревнование", completed: "Завершено" };
export default async function OrganizerTournamentPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return null;
  const { data: organizer } = await supabase.from("organizers").select("id").eq("user_id", user.id).maybeSingle(); if (!organizer) notFound();
  const { data: tournament } = await supabase.from("tournaments").select("id,name,date,city,venue,sport,description,entry_fee,registration_deadline,status,is_public").eq("id", id).eq("organizer_id", organizer.id).single(); if (!tournament) notFound();
  const [participants,categories,matches,mats] = await Promise.all([supabase.from("registrations").select("id",{count:"exact",head:true}).eq("tournament_id",id),supabase.from("categories").select("id",{count:"exact",head:true}).eq("tournament_id",id),supabase.from("matches").select("id",{count:"exact",head:true}).eq("tournament_id",id),supabase.from("mats").select("id",{count:"exact",head:true}).eq("tournament_id",id)]);
  return <main className="container dashboard-page"><div className="page-topline"><Link className="back-link" href="/organizer">← Мои соревнования</Link></div><header className="tournament-header"><div><div className="eyebrow">{tournament.sport}</div><h1>{tournament.name}</h1><p className="muted">{tournament.date} · {tournament.city}{tournament.venue?` · ${tournament.venue}`:""}</p></div><span className="status">{statusLabels[tournament.status]??tournament.status}</span></header>
  <nav className="tournament-nav">{[["Обзор",`/organizer/tournaments/${id}`],["Участники",`/organizer/tournaments/${id}/participants`],["Категории",`/organizer/tournaments/${id}/categories`],["Сетки",`/organizer/tournaments/${id}/brackets`],["Расписание",`/organizer/tournaments/${id}/schedule`],["Ковры",`/organizer/tournaments/${id}/mats`],["Проведение",`/organizer/tournaments/${id}/running`],["Результаты",`/organizer/tournaments/${id}/results`],["Настройки",`/organizer/tournaments/${id}/settings`]].map(([label,href])=><Link href={href} key={href}>{label}</Link>)}</nav>
  <section className="stat-grid"><div className="stat-card"><strong>{participants.count??0}</strong><span>Заявок</span></div><div className="stat-card"><strong>{categories.count??0}</strong><span>Категорий</span></div><div className="stat-card"><strong>{matches.count??0}</strong><span>Боёв</span></div><div className="stat-card"><strong>{mats.count??0}</strong><span>Ковров</span></div></section>
  <section className="panel"><h2>Обзор</h2><p className="muted">Настройте участников, категории, сетки, расписание и проведение в отдельных рабочих разделах.</p></section></main>;
}
