import Link from "next/link";
import { hasTournamentPermission, permissionDeniedPage } from "@/lib/tournament-permissions";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getLocale, getT } from "@/lib/i18n-server";
import ShareEventButton from "@/components/share-event-button";

export default async function OrganizerTournamentPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const t=await getT();const locale=await getLocale();const ru=locale==="ru";const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return null;if(!(await hasTournamentPermission(supabase,id,"overview")))return permissionDeniedPage();
 const {data:tournament}=await supabase.from("tournaments").select("id,name,date,city,venue,sport,description,entry_fee,registration_deadline,status,is_public,poster_url,regulations_text").eq("id",id).maybeSingle();if(!tournament)notFound();
 const [participants,categories,matches,mats,access]=await Promise.all([supabase.from("registrations").select("id",{count:"exact",head:true}).eq("tournament_id",id),supabase.from("categories").select("id",{count:"exact",head:true}).eq("tournament_id",id),supabase.from("matches").select("id",{count:"exact",head:true}).eq("tournament_id",id),supabase.from("mats").select("id",{count:"exact",head:true}).eq("tournament_id",id),Promise.all((["participants","categories","brackets","schedule"] as const).map(key=>hasTournamentPermission(supabase,id,key)))]);
 const statusLabels:Record<string,string>={draft:t.draft,registration_open:t.registrationOpen,registration_closed:t.registrationClosed,preparation:t.preparation,running:t.running,completed:t.completed};
 const shareEventLabel=ru?"Поделиться событием":"Жарыспен бөлісу";
 const shareRegulationLabel=ru?"Поделиться положением":"Ережемен бөлісу";
 const cards=[{count:participants.count??0,label:t.applications,href:"participants"},{count:categories.count??0,label:t.categories,href:"categories"},{count:matches.count??0,label:t.fights,href:"brackets"},{count:mats.count??0,label:t.matCount,href:"schedule"}];
 return <main className="container dashboard-page tournament-workspace"><header className="tournament-header"><div className="tournament-heading"><div className="eyebrow">{tournament.sport}</div><h1>{tournament.name}</h1><p className="muted">{tournament.date} · {tournament.city}{tournament.venue?` · ${tournament.venue}`:""}</p></div><span className="status">{statusLabels[tournament.status]??tournament.status}</span></header><div className="action-row tournament-actions">{tournament.is_public&&<><Link className="button-link primary" href={`/tournaments/${id}`} target="_blank">{shareEventLabel}</Link>{tournament.regulations_text&&<ShareEventButton title={`${tournament.name} — ${ru?"Положение соревнований":"Жарыс ережесі"}`} locale={locale} url={`/tournaments/${id}/regulations`} label={shareRegulationLabel}/>}</>}</div><section className="stat-grid tournament-stats">{cards.map((card,i)=>access[i]?<Link key={card.href} className="stat-card" href={`/organizer/tournaments/${id}/${card.href}`}><strong>{card.count}</strong><span>{card.label}</span></Link>:<details key={card.href} className="stat-card" style={{opacity:.45,cursor:"pointer"}}><summary style={{listStyle:"none",display:"flex",flexDirection:"column",gap:4}}><strong>{card.count}</strong><span>{card.label}</span></summary><span>Этот раздел недоступен для вашей роли.</span></details>)}</section><section className="panel tournament-overview"><div className="panel-kicker">{t.overview}</div><h2>{t.overview}</h2><p className="muted">{t.overviewText}</p><p className="muted">{ru?"Здесь турнир остаётся в вашем кабинете. Данные, афишу и положение можно менять после создания, а доступ к этому турниру можно выдать другим зарегистрированным организаторам.":"Бұл жарыс кабинетіңізде сақталады. Деректерді, афишаны және ережені жасағаннан кейін өзгертуге болады, ал жарысқа басқа тіркелген ұйымдастырушыларға қолжетімділік беруге болады."}</p></section></main>;
}
