import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getT } from "@/lib/i18n-server";

export default async function OrganizerTournamentPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const t=await getT();const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return null;
 const {data:tournament}=await supabase.from("tournaments").select("id,name,date,city,venue,sport,description,entry_fee,registration_deadline,status,is_public,poster_url").eq("id",id).maybeSingle();if(!tournament)notFound();
 const [participants,categories,matches,mats]=await Promise.all([supabase.from("registrations").select("id",{count:"exact",head:true}).eq("tournament_id",id),supabase.from("categories").select("id",{count:"exact",head:true}).eq("tournament_id",id),supabase.from("matches").select("id",{count:"exact",head:true}).eq("tournament_id",id),supabase.from("mats").select("id",{count:"exact",head:true}).eq("tournament_id",id)]);
 const statusLabels:Record<string,string>={draft:t.draft,registration_open:t.registrationOpen,registration_closed:t.registrationClosed,preparation:t.preparation,running:t.running,completed:t.completed};
 const nav:[[string,string],[string,string],[string,string],[string,string],[string,string],[string,string],[string,string],[string,string],[string,string],[string,string]]=[[t.overview,`/organizer/tournaments/${id}`],[t.participants,`/organizer/tournaments/${id}/participants`],[t.categories,`/organizer/tournaments/${id}/categories`],[t.brackets,`/organizer/tournaments/${id}/brackets`],[t.schedule,`/organizer/tournaments/${id}/schedule`],[t.mats,`/organizer/tournaments/${id}/mats`],[t.runningMode,`/organizer/tournaments/${id}/running`],[t.results,`/organizer/tournaments/${id}/results`],[t.settings,`/organizer/tournaments/${id}/settings`],["Команда / Команда",`/organizer/tournaments/${id}/team`]];
 return <main className="container dashboard-page"><div className="page-topline"><Link className="back-link" href="/organizer">← {t.backToTournaments}</Link></div><header className="tournament-header"><div><div className="eyebrow">{tournament.sport}</div><h1>{tournament.name}</h1><p className="muted">{tournament.date} · {tournament.city}{tournament.venue?` · ${tournament.venue}`:""}</p></div><span className="status">{statusLabels[tournament.status]??tournament.status}</span></header><div className="action-row"><Link className="button-link secondary" href={`/organizer/tournaments/${id}/settings`}>Редактировать турнир / Турнирді өңдеу</Link><Link className="button-link secondary" href={`/organizer/tournaments/${id}/team`}>Доступ команде / Командаға қолжетімділік</Link>{tournament.is_public&&<Link className="button-link secondary" href={`/tournaments/${id}`} target="_blank">Открыть публичную страницу</Link>}</div><nav className="tournament-nav">{nav.map(([label,href])=><Link href={href} key={href}>{label}</Link>)}</nav><section className="stat-grid"><div className="stat-card"><strong>{participants.count??0}</strong><span>{t.applications}</span></div><div className="stat-card"><strong>{categories.count??0}</strong><span>{t.categories}</span></div><div className="stat-card"><strong>{matches.count??0}</strong><span>{t.fights}</span></div><div className="stat-card"><strong>{mats.count??0}</strong><span>{t.matCount}</span></div></section><section className="panel"><h2>{t.overview}</h2><p className="muted">{t.overviewText}</p><p className="muted">Здесь турнир остаётся в вашем кабинете. Данные, афишу и положение можно менять после создания, а доступ к этому турниру можно выдать другим зарегистрированным организаторам.</p></section></main>;
}
